# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"m\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncreator_id\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"\x9c\x01\n\x0cPostResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreator_id\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\x12\x12\n\nis_private\x18\x07 \x01(\x08\x12\x0c\n\x04tags\x18\x08 \x03(\t\"-\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\xae\x01\n\x11UpdatePostRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\x05title\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nis_private\x18\x05 \x01(\x08H\x02\x88\x01\x01\x12\x0c\n\x04tags\x18\x06 \x03(\tB\x08\n\x06_titleB\x0e\n\x0c_descriptionB\r\n\x0b_is_private\"0\n\x11\x44\x65letePostRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"C\n\x10ListPostsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x10\n\x08per_page\x18\x03 \x01(\x05\"E\n\x11ListPostsResponse\x12!\n\x05posts\x18\x01 \x03(\x0b\x32\x12.post.PostResponse\x12\r\n\x05total\x18\x02 \x01(\x05\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xbd\x02\n\x0bPostService\x12;\n\nCreatePost\x12\x17.post.CreatePostRequest\x1a\x12.post.PostResponse\"\x00\x12\x35\n\x07GetPost\x12\x14.post.GetPostRequest\x1a\x12.post.PostResponse\"\x00\x12;\n\nUpdatePost\x12\x17.post.UpdatePostRequest\x1a\x12.post.PostResponse\"\x00\x12=\n\nDeletePost\x12\x17.post.DeletePostRequest\x1a\x14.post.DeleteResponse\"\x00\x12>\n\tListPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPOSTREQUEST']._serialized_start=20
  _globals['_CREATEPOSTREQUEST']._serialized_end=129
  _globals['_POSTRESPONSE']._serialized_start=132
  _globals['_POSTRESPONSE']._serialized_end=288
  _globals['_GETPOSTREQUEST']._serialized_start=290
  _globals['_GETPOSTREQUEST']._serialized_end=335
  _globals['_UPDATEPOSTREQUEST']._serialized_start=338
  _globals['_UPDATEPOSTREQUEST']._serialized_end=512
  _globals['_DELETEPOSTREQUEST']._serialized_start=514
  _globals['_DELETEPOSTREQUEST']._serialized_end=562
  _globals['_LISTPOSTSREQUEST']._serialized_start=564
  _globals['_LISTPOSTSREQUEST']._serialized_end=631
  _globals['_LISTPOSTSRESPONSE']._serialized_start=633
  _globals['_LISTPOSTSRESPONSE']._serialized_end=702
  _globals['_DELETERESPONSE']._serialized_start=704
  _globals['_DELETERESPONSE']._serialized_end=737
  _globals['_POSTSERVICE']._serialized_start=740
  _globals['_POSTSERVICE']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
