# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.promo_pb2 as promo__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in promo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PromoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePromo = channel.unary_unary(
                '/promo.PromoService/CreatePromo',
                request_serializer=promo__pb2.CreatePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.GetPromo = channel.unary_unary(
                '/promo.PromoService/GetPromo',
                request_serializer=promo__pb2.GetPromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.UpdatePromo = channel.unary_unary(
                '/promo.PromoService/UpdatePromo',
                request_serializer=promo__pb2.UpdatePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.PromoResponse.FromString,
                _registered_method=True)
        self.DeletePromo = channel.unary_unary(
                '/promo.PromoService/DeletePromo',
                request_serializer=promo__pb2.DeletePromoRequest.SerializeToString,
                response_deserializer=promo__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListPromos = channel.unary_unary(
                '/promo.PromoService/ListPromos',
                request_serializer=promo__pb2.ListPromosRequest.SerializeToString,
                response_deserializer=promo__pb2.ListPromosResponse.FromString,
                _registered_method=True)


class PromoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPromos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePromo,
                    request_deserializer=promo__pb2.CreatePromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'GetPromo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromo,
                    request_deserializer=promo__pb2.GetPromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'UpdatePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePromo,
                    request_deserializer=promo__pb2.UpdatePromoRequest.FromString,
                    response_serializer=promo__pb2.PromoResponse.SerializeToString,
            ),
            'DeletePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePromo,
                    request_deserializer=promo__pb2.DeletePromoRequest.FromString,
                    response_serializer=promo__pb2.DeleteResponse.SerializeToString,
            ),
            'ListPromos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPromos,
                    request_deserializer=promo__pb2.ListPromosRequest.FromString,
                    response_serializer=promo__pb2.ListPromosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'promo.PromoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('promo.PromoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/CreatePromo',
            promo__pb2.CreatePromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/GetPromo',
            promo__pb2.GetPromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/UpdatePromo',
            promo__pb2.UpdatePromoRequest.SerializeToString,
            promo__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/DeletePromo',
            promo__pb2.DeletePromoRequest.SerializeToString,
            promo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPromos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/promo.PromoService/ListPromos',
            promo__pb2.ListPromosRequest.SerializeToString,
            promo__pb2.ListPromosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
